CREATE DATABASE botanero_ventas;
USE botanero_ventas
CREATE TABLE categorias(
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	tipo ENUM("PLATILLO", "BEBIDA") NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	descripcion VARCHAR(255)
);

CREATE TABLE insumos(
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	codigo VARCHAR(100) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	descripcion VARCHAR(255) NOT NULL,
	precio DECIMAL(6,2) NOT NULL,
	tipo ENUM("PLATILLO", "BEBIDA") NOT NULL,
	categoria BIGINT UNSIGNED NOT NULL
);

CREATE TABLE informacion_negocio(
	nombre VARCHAR(100),
	telefono VARCHAR(15),
	numeroMesas TINYINT, 
	logo VARCHAR(255)
);

CREATE TABLE usuarios(
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	correo VARCHAR(100) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	telefono VARCHAR(20) NOT NULL,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE ventas(
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	idMesa TINYINT NOT NULL,
	cliente VARCHAR(100),
	fecha DATETIME NOT NULL,
	total DECIMAL(6,2) NOT NULL,
	pagado DECIMAL(6,2) NOT NULL,
	idUsuario BIGINT UNSIGNED NOT NULL
);

CREATE TABLE insumos_venta(
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	idInsumo BIGINT UNSIGNED NOT NULL,
	precio DECIMAL(6,2) NOT NULL,
	cantidad INT NOT NULL,
	idVenta BIGINT UNSIGNED
);


ALTER TABLE informacion_negocio ADD COLUMN logo VARCHAR(255);